// export const langObj = {
//   0: { english: "Zero", hausa: "sifili", yoruba: "òdo" },
//   1: { english: "one", hausa: "daya", yoruba: "ọ̀kan" },
//   2: { english: "two", hausa: "biyu", yoruba: "èjì " },
//   3: { english: "Three", hausa: "uku", yoruba: "ẹ̀ta" },
//   4: { english: "Four", hausa: "hudu", yoruba: "ẹ̀rin " },
//   5: { english: "Five", hausa: "biyar", yoruba: "àrún " },
//   6: { english: "Six", hausa: "shidda", yoruba: "ẹ̀fà " },
//   7: { english: "Seven", hausa: "bakwai", yoruba: "èje " },
//   8: { english: "Eight", hausa: "takwas", yoruba: "ẹ̀jọ " },
//   9: { english: "Nine", hausa: "tara", yoruba: "ẹ̀sán " },
//   10: { english: "Ten", hausa: "goma", yoruba: "ẹ̀wá " },
//   11: { english: "Eleven", hausa: "goma sha daya", yoruba: "oókànlá" },
//   12: { english: "Twelve", hausa: "goma sha biyu", yoruba: "eéjìlá" },
//   13: { english: "Thirteen", hausa: "goma sha uku", yoruba: "eétalá" },
//   14: { english: "Fourteen", hausa: "goma sha hudu", yoruba: "eérinlá" },
//   15: { english: "Fifteen", hausa: "goma sha biyar", yoruba: "ẹ́ẹdógún" },
//   16: { english: "Sixteen", hausa: "goma sha shidda", yoruba: "eérìndínlógún" },
//   17: {
//     english: "Seventeen",
//     hausa: "goma sha bakwai",
//     yoruba: "eétàdínlógún",
//   },
//   18: { english: "Eighteen", hausa: "goma sha takwas", yoruba: "eéjìdínlógún" },
//   19: { english: "Nineteen", hausa: "goma sha tara", yoruba: "oókàndínlógún" },
//   20: { english: "Twenty", hausa: "ashirin", yoruba: "ogún" },
//   21: {
//     english: "Twenty One",
//     hausa: "ashirin sha daya",
//     yoruba: "ọ̀kan le ni ogún ",
//   },
//   22: {
//     english: "Twenty Two",
//     hausa: "ashirin sha biyu",
//     yoruba: "èjì le ni ogún",
//   },
//   23: {
//     english: "Twenty Three",
//     hausa: "ashirin sha uku",
//     yoruba: "ẹ̀ta le ni ogún",
//   },
//   24: {
//     english: "Twenty Four",
//     hausa: "ashirin sha hudu",
//     yoruba: "ẹ̀rin le ni ogún",
//   },
//   25: {
//     english: "Twenty Five",
//     hausa: "ashirin sha daya",
//     yoruba: "àrún din ni ọgbọ̀n",
//   },
//   26: {
//     english: "Twenty Six",
//     hausa: "ashirin sha daya",
//     yoruba: "ẹ̀rin din ni ọgbọ̀n",
//   },
//   27: {
//     english: "Twenty Seven",
//     hausa: "ashirin sha daya",
//     yoruba: "ẹ̀ta din ni ọgbọ̀n",
//   },
//   28: {
//     english: "Twenty Eight",
//     hausa: "ashirin sha daya",
//     yoruba: "èjì din ni ọgbọ̀n",
//   },
//   29: {
//     english: "Twenty Nine",
//     hausa: "ashirin sha daya",
//     yoruba: "ọ̀kan din ni ọgbọ̀n",
//   },
//   30: { english: "Thirty", hausa: "talatin", yoruba: "ọgbọ̀n" },
//   31: {
//     english: "Thirty One",
//     hausa: "talatin sha daya",
//     yoruba: "ọ̀kan le ni ọgbọ̀n",
//   },
//   32: {
//     english: "Thirty Two",
//     hausa: "talatin sha biyu",
//     yoruba: "èjì le ni ọgbọ̀n ",
//   },
//   33: {
//     english: "Thirty Three",
//     hausa: "talatin sha uku",
//     yoruba: "ẹ̀ta le ni ọgbọ̀n ",
//   },
//   34: {
//     english: "Thirty Four",
//     hausa: "talatin sha hudu",
//     yoruba: "ẹ̀rin le ni ọgbọ̀",
//   },
//   35: {
//     english: "Thirty Five",
//     hausa: "talatin sha biyar",
//     yoruba: "àrún din ni ogójì",
//   },
//   36: {
//     english: "Thirty Six",
//     hausa: "talatin sha shidda",
//     yoruba: "ẹ̀rin din ni ogójì",
//   },
//   37: {
//     english: "Thirty Seven",
//     hausa: "talatin sha bakwai",
//     yoruba: "ẹ̀ta din ni ogójì",
//   },
//   38: {
//     english: "Thirty Eight",
//     hausa: "talatin sha takwas",
//     yoruba: "èjì din ni ogójì",
//   },
//   39: {
//     english: "Thirty Nine",
//     hausa: "talatin sha tara",
//     yoruba: "ọ̀kan din ni ogójì",
//   },
//   40: { english: "Forty", hausa: "arbain", yoruba: "ogójì" },
//   41: {
//     english: "Forty One",
//     hausa: "arbain sha daya",
//     yoruba: "ọ̀kan le ni ogójì",
//   },
//   42: {
//     english: "Forty Two",
//     hausa: "arbain sha daya",
//     yoruba: "èjì le ni ogójì",
//   },
//   43: {
//     english: "Forty Three",
//     hausa: "arbain sha daya",
//     yoruba: "ẹ̀ta le ni ogójì",
//   },
//   44: {
//     english: "Forty Four",
//     hausa: "arbain sha daya",
//     yoruba: "ẹ̀rin le ni ogójì",
//   },
//   45: {
//     english: "Forty Five",
//     hausa: "arbain sha daya",
//     yoruba: "àrún din ni àádọ́ta",
//   },
//   46: {
//     english: "Forty Six",
//     hausa: "arbain sha daya",
//     yoruba: "ẹ̀rin din ni àádọ́ta",
//   },
//   47: {
//     english: "Forty Seven",
//     hausa: "arbain sha daya",
//     yoruba: "ẹ̀ta din ni àádọ́ta",
//   },
//   48: {
//     english: "Forty Eight",
//     hausa: "arbain sha daya",
//     yoruba: "èjì din ni àádọ́ta",
//   },
//   49: {
//     english: "Forty Nine",
//     hausa: "arbain sha daya",
//     yoruba: "ọ̀kan din ni àádọ́ta",
//   },
//   50: { english: "Fifty", hausa: "hamsin", yoruba: "àádọ́ta" },
//   51: {
//     english: "Fifty One",
//     hausa: "hamsin sha daya",
//     yoruba: "ọ̀kan le ni àádọ́ta",
//   },
//   52: {
//     english: "Fifty Two",
//     hausa: "hamsin sha daya",
//     yoruba: "èjì le ni àádọ́ta",
//   },
//   53: {
//     english: "Fifty Three",
//     hausa: "hamsin sha daya",
//     yoruba: "ẹ̀ta le ni àádọ́ta",
//   },
//   54: {
//     english: "Fifty Four",
//     hausa: "hamsin sha daya",
//     yoruba: "ẹ̀rin le ni àádọ́ta",
//   },
//   55: {
//     english: "Fifty Five",
//     hausa: "hamsin sha daya",
//     yoruba: "àrún din ni ọgọ́ta",
//   },
//   56: {
//     english: "Fifty Six",
//     hausa: "hamsin sha daya",
//     yoruba: "ẹ̀rin din ni ọgọ́ta",
//   },
//   57: {
//     english: "Fifty Seven",
//     hausa: "hamsin sha daya",
//     yoruba: "ẹ̀ta din ni ọgọ́ta",
//   },
//   58: {
//     english: "Fifty Eight",
//     hausa: "hamsin sha daya",
//     yoruba: "èjì din ni ọgọ́ta",
//   },
//   59: {
//     english: "Fifty Nine",
//     hausa: "hamsin sha daya",
//     yoruba: "ọ̀kan din ni ọgọ́ta",
//   },
//   60: { english: "Sixty", hausa: "sittin", yoruba: "ọgọ́ta" },
//   61: {
//     english: "Sixty One",
//     hausa: "sittin sha daya",
//     yoruba: "ọ̀kan le ni ọgọ́ta",
//   },
//   62: {
//     english: "Sixty Two",
//     hausa: "sittin sha daya",
//     yoruba: "èjì le ni ọgọ́ta",
//   },
//   63: {
//     english: "Sixty Three",
//     hausa: "sittin sha daya",
//     yoruba: "ẹ̀ta le ni ọgọ́ta ",
//   },
//   64: {
//     english: "Sixty Four",
//     hausa: "sittin sha daya",
//     yoruba: "ẹ̀rin le ni ọgọ́ta",
//   },
//   65: {
//     english: "Sixty Five",
//     hausa: "sittin sha daya",
//     yoruba: "àrún din ni àádọ́rin ",
//   },
//   66: {
//     english: "Sixty Six",
//     hausa: "sittin sha daya",
//     yoruba: "ẹ̀rin din ni àádọ́rin",
//   },
//   67: {
//     english: "Sixty Seven",
//     hausa: "sittin sha daya",
//     yoruba: "ẹ̀ta din ni àádọ́rin",
//   },
//   68: {
//     english: "Sixty Eight",
//     hausa: "sittin sha daya",
//     yoruba: "èjì din ni àádọ́rin",
//   },
//   69: {
//     english: "Sixty Nine",
//     hausa: "sittin sha daya",
//     yoruba: "ọ̀kan din ni àádọ́rin ",
//   },
//   70: { english: "Seventy", hausa: "sabain", yoruba: "àádọ́rin" },
//   71: {
//     english: "Seventy One",
//     hausa: "sabain sha daya",
//     yoruba: "ọ̀kan le ni àádọ́rin",
//   },
//   72: {
//     english: "Seventy Two",
//     hausa: "sabain sha daya",
//     yoruba: "èjì le ni àádọ́rin",
//   },
//   73: {
//     english: "Seventy Three",
//     hausa: "sabain sha daya",
//     yoruba: "ẹ̀ta le ni àádọ́rin",
//   },
//   74: {
//     english: "Seventy Four",
//     hausa: "sabain sha daya",
//     yoruba: "ẹ̀rin le ni àádọ́rin",
//   },
//   75: {
//     english: "Seventy Five",
//     hausa: "sabain sha daya",
//     yoruba: "àrún din ni ọgọ́rin",
//   },
//   76: {
//     english: "Seventy Six",
//     hausa: "sabain sha daya",
//     yoruba: "oẹ̀rin din ni ọgọ́ringún",
//   },
//   77: {
//     english: "Seventy Seven",
//     hausa: "sabain sha daya",
//     yoruba: "ẹ̀ta din ni ọgọ́rin",
//   },
//   78: {
//     english: "Seventy Eight",
//     hausa: "sabain sha daya",
//     yoruba: "èjì din ni ọgọ́rin",
//   },
//   79: {
//     english: "Seventy Nine",
//     hausa: "sabain sha daya",
//     yoruba: "ọ̀kan din ni ọgọ́rin",
//   },
//   80: { english: "Eighty", hausa: "tamanin", yoruba: "ọgọ́rin" },
//   81: {
//     english: "Eighty One",
//     hausa: "tamanin sha daya",
//     yoruba: "ọ̀kan le ni ọgọ́rin",
//   },
//   82: {
//     english: "Eighty Two",
//     hausa: "tamanin sha daya",
//     yoruba: "ẹ̀ji le ni ọgọ́rin",
//   },
//   83: {
//     english: "Eighty Three",
//     hausa: "tamanin sha daya",
//     yoruba: "ẹ̀ta le ni ọgọ́rin",
//   },
//   84: {
//     english: "Eighty Four",
//     hausa: "tamanin sha daya",
//     yoruba: "ẹ̀rin le ni ọgọ́rin",
//   },
//   85: {
//     english: "Eighty Five",
//     hausa: "tamanin sha daya",
//     yoruba: "àrún din ni àádọ́rùn",
//   },
//   86: {
//     english: "Eighty Six",
//     hausa: "tamanin sha daya",
//     yoruba: "ẹ̀rin din ni àádọ́rùn",
//   },
//   87: {
//     english: "Eighty Seven",
//     hausa: "tamanin sha daya",
//     yoruba: "ẹ̀ta din ni àádọ́rùn",
//   },
//   88: {
//     english: "Eighty Eight",
//     hausa: "tamanin sha daya",
//     yoruba: "èjì din ni àádọ́rùn",
//   },
//   89: {
//     english: "Eighty Nine",
//     hausa: "tamanin sha daya",
//     yoruba: "ọ̀kan din ni àádọ́rùn",
//   },
//   90: { english: "Ninety", hausa: "tasani", yoruba: "àádọ́rùn" },
//   91: {
//     english: "Ninety One",
//     hausa: "tasani sha daya",
//     yoruba: "ọ̀kan le ni àádọ́rùn",
//   },
//   92: {
//     english: "Ninety Two",
//     hausa: "tasani sha daya",
//     yoruba: "èjì le ni àádọ́rùn",
//   },
//   93: {
//     english: "Ninety Three",
//     hausa: "tasani sha daya",
//     yoruba: "ẹ̀ta le ni àádọ́rùn",
//   },
//   94: {
//     english: "Ninety Four",
//     hausa: "tasani sha daya",
//     yoruba: "ẹ̀rin le ni àádọ́rùn",
//   },
//   95: {
//     english: "Ninety Five",
//     hausa: "tasani sha daya",
//     yoruba: "àrún din ni ọgọ́rùn",
//   },
//   96: {
//     english: "Ninety Six",
//     hausa: "tasani sha daya",
//     yoruba: "ẹ̀rin din ni ọgọ́rùn",
//   },
//   97: {
//     english: "Ninety Seven",
//     hausa: "tasani sha daya",
//     yoruba: "ẹ̀ta din ni ọgọ́rùn",
//   },
//   98: {
//     english: "Ninety Eight",
//     hausa: "tasani sha daya",
//     yoruba: "èjì din ni ọgọ́rùn ",
//   },
//   99: {
//     english: "Ninety Nine",
//     hausa: "tasani sha daya",
//     yoruba: "ọ̀kan din ni ọgọ́rùn ",
//   },
//   100: { english: "Hundred", hausa: "dari", yoruba: "ọgọ́rùn " },
// };

export const langObj = {
  0: { english: "Zero", hausa: "sifili", yoruba: "òdo" },
  1: { english: "one", hausa: "daya", yoruba: "ọ̀kan" },
  2: { english: "two", hausa: "biyu", yoruba: "èjì " },
  3: { english: "Three", hausa: "uku", yoruba: "ẹ̀ta" },
  4: { english: "Four", hausa: "hudu", yoruba: "ẹ̀rin " },
  5: { english: "Five", hausa: "biyar", yoruba: "àrún " },
  6: { english: "Six", hausa: "shidda", yoruba: "ẹ̀fà " },
  7: { english: "Seven", hausa: "bakwai", yoruba: "èje " },
  8: { english: "Eight", hausa: "takwas", yoruba: "ẹ̀jọ " },
  9: { english: "Nine", hausa: "tara", yoruba: "ẹ̀sán " },
  10: { english: "Ten", hausa: "goma", yoruba: "ẹ̀wá " },
  11: { english: "Eleven", hausa: "goma sha daya", yoruba: "oókànlá" },
  12: { english: "Twelve", hausa: "goma sha biyu", yoruba: "eéjìlá" },
  13: { english: "Thirteen", hausa: "goma sha uku", yoruba: "eétalá" },
  14: { english: "Fourteen", hausa: "goma sha hudu", yoruba: "eérinlá" },
  15: { english: "Fifteen", hausa: "goma sha biyar", yoruba: "ẹ́ẹdógún" },
  16: { english: "Sixteen", hausa: "goma sha shidda", yoruba: "eérìndínlógún" },
  17: {
    english: "Seventeen",
    hausa: "goma sha bakwai",
    yoruba: "eétàdínlógún",
  },
  18: { english: "Eighteen", hausa: "goma sha takwas", yoruba: "eéjìdínlógún" },
  19: { english: "Nineteen", hausa: "goma sha tara", yoruba: "oókàndínlógún" },
  20: { english: "Twenty", hausa: "ashirin", yoruba: "ogún" },
  30: { english: "Thirty", hausa: "talatin", yoruba: "ọgbọ̀n" },
  40: { english: "Forty", hausa: "arbain", yoruba: "ogójì" },
  50: { english: "Fifty", hausa: "hamsin", yoruba: "àádọ́ta" },
  60: { english: "Sixty", hausa: "sittin", yoruba: "ọgọ́ta" },
  70: { english: "Seventy", hausa: "sabain", yoruba: "àádọ́rin" },
  80: { english: "Eighty", hausa: "tamanin", yoruba: "ọgọ́rin" },
  90: { english: "Ninety", hausa: "tasani", yoruba: "àádọ́rùn" },
  100: { english: "Hundred", hausa: "dari", yoruba: "ọgọ́rùn " },
};
