export const langObj = {
  0: { english: "Zero", hausa: "sifili", yoruba: "òdo" },
  1: { english: "One", hausa: "daya", yoruba: "ọ̀kan" },
  2: { english: "Two", hausa: "biyu", yoruba: "èjì " },
  3: { english: "Three", hausa: "uku", yoruba: "ẹ̀ta" },
  4: { english: "Four", hausa: "hudu", yoruba: "ẹ̀rin " },
  5: { english: "Five", hausa: "biyar", yoruba: "àrún " },
  6: { english: "Six", hausa: "shidda", yoruba: "ẹ̀fà " },
  7: { english: "Seven", hausa: "bakwai", yoruba: "èje " },
  8: { english: "Eight", hausa: "takwas", yoruba: "ẹ̀jọ " },
  9: { english: "Nine", hausa: "tara", yoruba: "ẹ̀sán " },
  10: { english: "Ten", hausa: "goma", yoruba: "ẹ̀wá " },
  11: { english: "Eleven", hausa: "goma sha daya", yoruba: "oókànlá" },
  12: { english: "Twelve", hausa: "goma sha biyu", yoruba: "eéjìlá" },
  13: { english: "Thirteen", hausa: "goma sha uku", yoruba: "eétalá" },
  14: { english: "Fourteen", hausa: "goma sha hudu", yoruba: "eérinlá" },
  15: { english: "Fifteen", hausa: "goma sha biyar", yoruba: "ẹ́ẹdógún" },
  16: { english: "Sixteen", hausa: "goma sha shidda", yoruba: "eérìndínlógún" },
  17: {
    english: "Seventeen",
    hausa: "goma sha bakwai",
    yoruba: "eétàdínlógún",
  },
  18: { english: "Eighteen", hausa: "goma sha takwas", yoruba: "eéjìdínlógún" },
  19: { english: "Nineteen", hausa: "goma sha tara", yoruba: "oókàndínlógún" },
  20: { english: "Twenty", hausa: "ashirin", yoruba: "ogún" },
  30: { english: "Thirty", hausa: "talatin", yoruba: "ọgbọ̀n" },
  40: { english: "Forty", hausa: "arbain", yoruba: "ogójì" },
  50: { english: "Fifty", hausa: "hamsin", yoruba: "àádọ́ta" },
  60: { english: "Sixty", hausa: "sittin", yoruba: "ọgọ́ta" },
  70: { english: "Seventy", hausa: "sabain", yoruba: "àádọ́rin" },
  80: { english: "Eighty", hausa: "tamanin", yoruba: "ọgọ́rin" },
  90: { english: "Ninety", hausa: "tasani", yoruba: "àádọ́rùn" },
  100: { english: "Hundred", hausa: "dari", yoruba: "ọgọ́rùn " },
};
